### ISSUE TITLE
local IP address is appended to the heimdall IP address

### ISSUE THREAD

**Issue by Fitz-o** [jsegaert/iocage-plugin-heimdall#1]
For example:
If Heimdall is hosted at 10.0.0.10 and my plex is 10.0.0.50 then when I click on the Plex icon, I'm taken to 10.0.0.10/10.0.0.50 which doesn't resolve obviously.

**Comment by jsegaert** [comment]
Hmm... I have a "Plex" application but it's working fine.  What do you have in the URL field? 
Be sure to enter the full URL, **including the protocol**, e.g.  'http://10.0.0.50:32400/'

**Comment by Fitz-o** [comment]
Maybe we're OK then. Looks like I just need to put the http://. Brain fart. Sorry for the trouble.
